# Generated by Django 4.1 on 2022-10-17 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('wishNum', models.BigAutoField(primary_key=True, serialize=False, verbose_name='장바구니 번호')),
                ('prodNum', models.ForeignKey(db_column='prodNum', on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('userId', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, to='member.member')),
            ],
        ),
    ]
