# Generated by Django 4.1 on 2022-10-28 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('recommendNum', models.BigAutoField(primary_key=True, serialize=False, verbose_name='추천상품번호')),
                ('userId', models.CharField(max_length=50, verbose_name='아이디')),
                ('prodList', models.CharField(max_length=150, null=True, verbose_name='추천 상품 리스트')),
                ('status', models.CharField(max_length=20, verbose_name='추천상태')),
            ],
        ),
    ]
