# Generated by Django 4.1 on 2022-10-17 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Qnaboard',
            fields=[
                ('qnaNum', models.AutoField(primary_key=True, serialize=False, verbose_name='글번호')),
                ('userId', models.CharField(max_length=20, verbose_name='작성자')),
                ('qnaTitle', models.CharField(max_length=1000, verbose_name='글제목')),
                ('qnaContent', models.TextField(verbose_name='글내용')),
                ('qnaScore', models.IntegerField(default=0, verbose_name='조회수')),
                ('qnaDate', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('qnaIp', models.CharField(max_length=15, verbose_name='아이피')),
                ('reply_title', models.CharField(max_length=1000, null=True, verbose_name='댓글제목')),
                ('reply_content', models.TextField(null=True, verbose_name='관리자 댓글')),
            ],
        ),
    ]
