# Generated by Django 4.1 on 2022-10-17 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviewboard',
            fields=[
                ('reviewNum', models.AutoField(primary_key=True, serialize=False, verbose_name='글번호')),
                ('userId', models.CharField(max_length=20, verbose_name='작성자')),
                ('reviewDate', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('reviewTitle', models.CharField(max_length=1000, verbose_name='글제목')),
                ('reviewContent', models.TextField(verbose_name='글내용')),
                ('reviewIp', models.CharField(max_length=15, verbose_name='아이피')),
                ('reviewPhoto', models.ImageField(null=True, upload_to='reviews')),
                ('prodNum', models.ForeignKey(db_column='prodNum', on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
